### ISSUE TITLE
extra tack

### ISSUE THREAD

**Issue by Friesianss** [s3xi/Horses-4-Wiki#10]
Extra tack like the bridle girth etc, won't go into the slots anymore for me? is this just me or...?

**Comment by s3xi** [comment]
If it is the old tack items, they will not work. If it is the new tack items, I will have to look into this.

**Comment by Friesianss** [comment]
I do know I tried the martingale that wouldn't.

**Comment by Friesianss** [comment]
Yeah it was old tack, all good.
