### ISSUE TITLE
can't respond to questions?? help??

### ISSUE THREAD

**Issue by glowcrown** [s3xi/Horses-4-Wiki#30]
I just joined this server today after looking for a equestrian server to play on. After spawning at the hub, the chat told me to type 'start' into the chat to begin an interview questionnaire. However, when I did so, the chat told me I wasn't allowed to speak. I logged out and logged back in and the first question appeared. Thinking I had fixed it, I tried answering the question but the same 'you cannot type in chat' message appeared. A mod later encouraged me to type start, but I couldn't tell her that I couldn't speak whatsoever. Am i typing in the wrong area?? I'm not sure what I'm doing wrong. Please help!! my name ign is glowcrown, by the way.

**Comment by s3xi** [comment]
Please rejoin the game and get our discord link, we can help there.

**Comment by glowcrown** [comment]
i can't get the discord link either. i literally can't type anything in the chat without a message saying i can't type anything until I've answered the questions. I tried just manually googling it but all I can find is your Enjin website and the discord section doesn't lead me anywhere

**Comment by glowcrown** [comment]
hey, sorry to be a bother, but I still am unable to get the discord link or answer any of the questions :(

**Comment by s3xi** [comment]
join and ill give you the link

**Comment by glowcrown** [comment]
im sorry! I don't get alerts for this. What time are you usually on the server?

**Comment by s3xi** [comment]
Im on now if youre around

**Comment by s3xi** [comment]
here, join https://discord.gg/vHq7bHA
