### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by sirianr7** [s3xi/Horses-4-Wiki#31]
Hey!
I tried logging in several times on equitopia but it doesn't work.
Everytime I try to log in it says: Connection timed out: no further information
I've checked my internet, but that wasn't the problem, because other servers do work
I did see on the enjin that other people are playing equitopia right now...
Does anyone know how to fix this?

**Comment by s3xi** [comment]
This is for issues with the plugin, not the server.
