### ISSUE TITLE
OCD WARNING

### ISSUE THREAD

**Issue by LonedxWolf** [s3xi/Horses-4-Wiki#6]
FIX MY PREFIXES YOU USELESS DUMP OF GLITTAR

**Comment by s3xi** [comment]
Please use less caps when reporting issues/bugs and provide a brief description of what is actually happening.

**Comment by LonedxWolf** [comment]
ILL MUTE YE IN A MINUTE YOU SPECKY CUNT

**Comment by s3xi** [comment]
This should be solved now.
