### ISSUE TITLE
/h market

### ISSUE THREAD

**Issue by itsraggel** [s3xi/Horses-4-Wiki#9]
This is a great feature to the server and allows quick access towards buying and selling horses but I found out that I could buy a 3D barrel racer and could not bid or buy a 3.9 3D Show jumper. Probably just a glitch, but ya.

**Comment by s3xi** [comment]
I believe the source of this bug is that, while you can own the very bottom of D3, being 35.00, your rank cannot own higher than that, so the D3 on the market was likely greater than 35.00
